### ISSUE TITLE
ICTextView changes position after rotate device from Portrait to Landscape mode.

### ISSUE THREAD

**Issue by DimonDeveloper** [Exile90/ICTextView#12]
After rotate device from Portrait to Landscape mode, ICTextView every time scroll a little lower.

**Comment by IvanoBilenchi** [comment]
This is actually the behavior of the standard `UITextView`, as can be seen in the [TextViewSample_UITextView.zip](https://github.com/Exile90/ICTextView/files/110826/TextViewSample_UITextView.zip) archive I linked in issue #11.

I'm marking this as a proposed enhancement.

**Comment by DimonDeveloper** [comment]
Oh i see, sorry to bother.
