### ISSUE TITLE
consideringInsets:YES results in no scrolling at all.

### ISSUE THREAD

**Issue by jacklink01** [Exile90/ICTextView#8]
When I use consideringInsets:YES, my text view does not scroll at all in iOS 8.4.

**Comment by Exile90** [comment]
@jacklink01 The included sample app works fine in iOS 8.4. I'm also using ICTextView in a production application, and it's scrolling fine with `consideringInsets:YES` in 8.4.

Are you setting ICTextView's contentInsets correctly? See the sample app for a working example.
